server:
  port: 8080

spring:
  application:
    name: image-ingestion-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    # url: ${SPRING_DATASOURCE_URL}
    url: jdbc:postgresql://localhost/coin_id?host=/cloudsql/gcp-web-example:asia-southeast1:coin-id-pg
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

gcp:
  project-id: ${GOOGLE_CLOUD_PROJECT:coinid-local}
  storage:
    bucket: ${GCS_BUCKET:coin-images-dev}
  pubsub:
    topic: ${PUBSUB_TOPIC:coin-image-uploaded}

management:
  endpoints:
    web:
      exposure:
        include: health,info
