server:
  port: 8088

spring:
  application:
    name: user-catalog-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://34.124.164.12:5432/coin_id?host=/cloudsql/gcp-web-example:asia-southeast1:coin-id-pg}
    username: ${SPRING_DATASOURCE_USERNAME:coinid}
    password: ${SPRING_DATASOURCE_PASSWORD:P@ssw0rd99}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me-please-32-chars-min}
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

# spring.datasource.url=jdbc:postgresql://localhost/coin_id?host=/cloudsql/gcp-web-example:asia-southeast1:coin-id-pg
# spring.datasource.username=YOUR_USERNAME
# spring.datasource.password=YOUR_PASSWORD