steps:
  # 1. Test & Build Java Application
  - id: image-ingestion-test-build
    name: maven:3.9-eclipse-temurin-17
    dir: services/image-ingestion-service
    entrypoint: mvn
    args: ['-X', '-B', 'clean', 'verify']

  - id: image-ingestion-docker-build
    name: gcr.io/cloud-builders/docker
    dir: services/image-ingestion-service
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/image-ingestion-service:$SHORT_SHA'
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/image-ingestion-service:latest'
      - .

  # 2. Push Image with commit SHA
  - id: image-ingestion-docker-push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/image-ingestion-service:$SHORT_SHA'



  # 3. Deploy to Cloud Run
  - id: deploy-image-ingestion
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - coin-id-image-ingestion
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/image-ingestion-service:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--set-env-vars=DB_URL=${_DB_URL},DB_USERNAME=${_DB_USERNAME},DB_PASSWORD=${_DB_PASSWORD}'
      - '--set-secrets=SPRING_DATASOURCE_PASSWORD=coin-id-db-password:latest'
      - '--platform=managed'
      - '--quiet'


images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/image-ingestion-service:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 2400s

substitutions:
  _REGION: asia-southeast1
  _REPO: coin-id-repo
  _DB_URL: jdbc:postgresql://localhost/coin_id?host=/cloudsql/gcp-web-example:asia-southeast1:coin-id-pg
  _DB_USERNAME: coinid
  _DB_PASSWORD: P@ssw0rd99