# Infrastructure pipeline: provision/update GCP resources with Terraform.
steps:
  - id: terraform-init-validate-plan-apply
    name: hashicorp/terraform:1.7
    dir: infrastructure/terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false

        terraform import google_pubsub_topic.coin_image_uploaded \
        projects/$PROJECT_ID/topics/coin-image-uploaded

        terraform import google_sql_database_instance.coin_id_pg \
        projects/$PROJECT_ID/instances/coin-id-pg

        terraform import \
        google_firebase_hosting_site.frontend \
        projects/$PROJECT_ID/sites/$_FIREBASE_SITE_ID        

        terraform validate
        terraform plan -input=false -out=tfplan \
          -var="project_id=$PROJECT_ID" \
          -var="region=${_REGION}" \
          -var="db_password=${_DB_PASSWORD}" \
          -var="vertex_ai_endpoint=${_VERTEX_AI_ENDPOINT}"
        terraform apply -input=false -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 2400s

substitutions:
  _REGION: asia-southeast1
  _DB_PASSWORD: 'P@ssw0rd99'
  _VERTEX_AI_ENDPOINT: ''
  _FIREBASE_SITE_ID: 'coin_id_frontend'